version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:3.0.2-node
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/scribble-by-anmol-kumar
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      RAILS_ENV: "test"
      RACK_ENV: "test"

    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - run:
          bundle check --path=vendor/bundle || bundle install
          --path=vendor/bundle --jobs=4 --retry=3
      - run:
          chmod a+x ./bin/yarn && ./bin/yarn install --cache-folder
          vendor/node_modules
      - run: bundle exec rubocop
      - run:
          npx prettier "./app/javascript/src/**/*.{js,jsx,json}" && npx eslint
          "./app/javascript/src/**/*.{js,jsx,json}"
      - run: cp config/database.yml.ci config/database.yml
      - run: sudo apt update && sudo apt-get install postgresql-client
      - run: bundle exec rails db:create db:schema:load --trace
      - run: chmod a+x ./bin/webpack && ./bin/webpack
      - run: bundle exec rails webpacker:compile
      - run:
          shell: /bin/bash
          command: bundle exec rake db:test:prepare && bundle exec rails t -v
workflows:
  version: 2
  commit:
    jobs:
      - build
